from datetime import datetime
from zoneinfo import ZoneInfo

from src.formatter import format_report
from src.stores.base import StoreResult


def _make_time():
    return datetime(2026, 2, 11, 9, 0, 0, tzinfo=ZoneInfo("Asia/Manila"))


def test_full_report_all_stores():
    results = [
        StoreResult("App Store", daily_downloads=1234, total_downloads=45678, data_date="Feb 10"),
        StoreResult("Google Play", daily_downloads=5678, total_downloads=234567, data_date="Feb 10"),
    ]
    msg = format_report(results, _make_time())

    assert "<pre>" in msg
    assert "</pre>" in msg
    assert "B-Ticket Daily Download Report" in msg
    assert "2026-02-11" in msg
    assert "1,234" in msg
    assert "45,678" in msg
    assert "5,678" in msg
    assert "234,567" in msg
    # Grand totals
    assert "6,912" in msg      # 1234 + 5678
    assert "280,245" in msg    # 45678 + 234567
    assert "Auto-generated by AI" in msg
    assert "09:00 AM PHT" in msg


def test_partial_failure_one_store():
    results = [
        StoreResult("App Store", daily_downloads=100, total_downloads=500, data_date="Feb 10"),
        StoreResult("Google Play", error_message="API timeout"),
    ]
    msg = format_report(results, _make_time())

    assert "100" in msg
    assert "Unavailable" in msg
    assert "500" in msg


def test_all_stores_failed():
    results = [
        StoreResult("App Store", error_message="Auth failed"),
        StoreResult("Google Play", error_message="Timeout"),
    ]
    msg = format_report(results, _make_time())

    assert "All data sources are currently unavailable" in msg
    assert "2026-02-11" in msg


def test_number_formatting():
    results = [
        StoreResult("App Store", daily_downloads=1000000, total_downloads=9999999, data_date="Feb 10"),
    ]
    msg = format_report(results, _make_time())

    assert "1,000,000" in msg
    assert "9,999,999" in msg


def test_zero_downloads():
    results = [
        StoreResult("App Store", daily_downloads=0, total_downloads=500, data_date="Feb 10"),
    ]
    msg = format_report(results, _make_time())

    assert "0" in msg
    assert "500" in msg
