from datetime import datetime
from typing import List, Optional

from src.stores.base import StoreResult

STORE_ICONS = {
    "App Store": "\U0001f34e",
    "Google Play": "\U0001f916",
}


def _fmt(value: Optional[int]) -> str:
    """Format a number with commas, or 'N/A' if None."""
    if value is None:
        return "N/A"
    return f"{value:,}"


def format_report(results: List[StoreResult], report_time: datetime) -> str:
    """Format store results into an HTML message for Telegram."""
    all_failed = all(r.error_message and r.daily_downloads is None for r in results)

    if all_failed:
        return (
            "<pre>"
            "\u26a0\ufe0f B-Ticket Download Report\n"
            f"\U0001f4c5 {report_time.strftime('%Y-%m-%d')}\n"
            "\n"
            "All data sources are currently unavailable.\n"
            "Please check the GitHub Actions logs for details.\n"
            "\n"
            f"Auto-generated by AI\n"
            f"{report_time.strftime('%I:%M %p PHT')}"
            "</pre>"
        )

    lines = [
        "\U0001f4ca B-Ticket Daily Download Report",
        f"\U0001f4c5 {report_time.strftime('%Y-%m-%d')}",
        "",
    ]

    daily_total = 0
    cumulative_total = 0
    daily_total_valid = False
    cumulative_total_valid = False

    for r in results:
        icon = STORE_ICONS.get(r.store_name, "\U0001f4e6")

        if r.error_message and r.daily_downloads is None:
            date_note = ""
            today_str = "\u26a0\ufe0f Unavailable"
            total_str = "\u26a0\ufe0f Unavailable"
        else:
            date_note = f" (data: {r.data_date})" if r.data_date else ""
            today_str = _fmt(r.daily_downloads)
            total_str = _fmt(r.total_downloads)
            if r.daily_downloads is not None:
                daily_total += r.daily_downloads
                daily_total_valid = True
            if r.total_downloads is not None:
                cumulative_total += r.total_downloads
                cumulative_total_valid = True

        lines.append(f"{icon} {r.store_name}{date_note}")
        lines.append(f"   Today: {today_str} | Total: {total_str}")
        lines.append("")

    lines.append("\u2501" * 30)
    lines.append(
        f"\U0001f4c8 Total Today: {_fmt(daily_total if daily_total_valid else None)}"
    )
    lines.append(
        f"\U0001f4e6 Grand Total: {_fmt(cumulative_total if cumulative_total_valid else None)}"
    )
    lines.append("")
    lines.append(f"Auto-generated by AI")
    lines.append(f"{report_time.strftime('%I:%M %p PHT')}")
    lines.append("")
    lines.append("Note: Data may be delayed up to")
    lines.append("5 days due to store reporting")
    lines.append("policy.")

    return "<pre>" + "\n".join(lines) + "</pre>"
