from datetime import datetime
from typing import List, Optional

from src.stores.base import StoreResult

STORE_ICONS = {
    "App Store": "\U0001f34e",
    "Google Play": "\U0001f916",
}


def _fmt(value: Optional[int]) -> str:
    """Format a number with commas, or 'N/A' if None."""
    if value is None:
        return "N/A"
    return f"{value:,}"


def format_report(results: List[StoreResult], report_time: datetime) -> str:
    """Format store results into an HTML message for Telegram."""
    all_failed = all(r.error_message and r.daily_downloads is None for r in results)

    if all_failed:
        return (
            "<pre>"
            "\u26a0\ufe0f B-Ticket Download Report\n"
            f"\U0001f4c5 {report_time.strftime('%Y-%m-%d')}\n"
            "\n"
            "All data sources are currently unavailable.\n"
            "Please check the GitHub Actions logs for details.\n"
            "\n"
            "\u2501" * 30 + "\n"
            "\n"
            "\u26a0\ufe0f B-Ticket \u30c0\u30a6\u30f3\u30ed\u30fc\u30c9\u30ec\u30dd\u30fc\u30c8\n"
            "\n"
            "\u5168\u3066\u306e\u30c7\u30fc\u30bf\u30bd\u30fc\u30b9\u304c\u73fe\u5728\u5229\u7528\u3067\u304d\u307e\u305b\u3093\u3002\n"
            "GitHub Actions\u306e\u30ed\u30b0\u3092\u3054\u78ba\u8a8d\u304f\u3060\u3055\u3044\u3002\n"
            "\n"
            f"AI\u81ea\u52d5\u751f\u6210\n"
            f"{report_time.strftime('%I:%M %p PHT')}"
            "</pre>"
        )

    # Compute totals
    daily_total = 0
    cumulative_total = 0
    daily_total_valid = False
    cumulative_total_valid = False

    for r in results:
        if not (r.error_message and r.daily_downloads is None):
            if r.daily_downloads is not None:
                daily_total += r.daily_downloads
                daily_total_valid = True
            if r.total_downloads is not None:
                cumulative_total += r.total_downloads
                cumulative_total_valid = True

    # English section
    lines = [
        "\U0001f4ca B-Ticket Daily Download Report",
        f"\U0001f4c5 {report_time.strftime('%Y-%m-%d')}",
        "",
    ]

    for r in results:
        icon = STORE_ICONS.get(r.store_name, "\U0001f4e6")

        if r.error_message and r.daily_downloads is None:
            date_note = ""
            today_str = "\u26a0\ufe0f Unavailable"
            total_str = "\u26a0\ufe0f Unavailable"
        else:
            date_note = f" (data: {r.data_date})" if r.data_date else ""
            today_str = _fmt(r.daily_downloads)
            total_str = _fmt(r.total_downloads)

        lines.append(f"{icon} {r.store_name}{date_note}")
        lines.append(f"   Today: {today_str} | Total: {total_str}")
        lines.append("")

    lines.append("\u2501" * 30)
    lines.append(
        f"\U0001f4c8 Total Today: {_fmt(daily_total if daily_total_valid else None)}"
    )
    lines.append(
        f"\U0001f4e6 Grand Total: {_fmt(cumulative_total if cumulative_total_valid else None)}"
    )
    lines.append("")
    lines.append("Auto-generated by AI")
    lines.append(report_time.strftime('%I:%M %p PHT'))
    lines.append("")
    lines.append("Note: Data may be delayed up to")
    lines.append("5 days due to store reporting")
    lines.append("policy.")

    # Japanese section
    lines.append("")
    lines.append("\u2501" * 30)
    lines.append("")
    lines.append("\U0001f4ca B-Ticket \u65e5\u6b21\u30c0\u30a6\u30f3\u30ed\u30fc\u30c9\u30ec\u30dd\u30fc\u30c8")
    lines.append(f"\U0001f4c5 {report_time.strftime('%Y-%m-%d')}")
    lines.append("")

    for r in results:
        icon = STORE_ICONS.get(r.store_name, "\U0001f4e6")

        if r.error_message and r.daily_downloads is None:
            date_note = ""
            today_str = "\u26a0\ufe0f \u53d6\u5f97\u4e0d\u53ef"
            total_str = "\u26a0\ufe0f \u53d6\u5f97\u4e0d\u53ef"
        else:
            date_note = f" (\u30c7\u30fc\u30bf: {r.data_date})" if r.data_date else ""
            today_str = _fmt(r.daily_downloads)
            total_str = _fmt(r.total_downloads)

        lines.append(f"{icon} {r.store_name}{date_note}")
        lines.append(f"   \u4eca\u65e5: {today_str} | \u7d2f\u8a08: {total_str}")
        lines.append("")

    lines.append("\u2501" * 30)
    lines.append(
        f"\U0001f4c8 \u4eca\u65e5\u306e\u5408\u8a08: {_fmt(daily_total if daily_total_valid else None)}"
    )
    lines.append(
        f"\U0001f4e6 \u7dcf\u30c0\u30a6\u30f3\u30ed\u30fc\u30c9\u6570: {_fmt(cumulative_total if cumulative_total_valid else None)}"
    )
    lines.append("")
    lines.append("AI\u81ea\u52d5\u751f\u6210")
    lines.append(report_time.strftime('%I:%M %p PHT'))
    lines.append("")
    lines.append("\u6ce8: \u30b9\u30c8\u30a2\u306e\u30ec\u30dd\u30fc\u30c8\u30dd\u30ea\u30b7\u30fc\u306b\u3088\u308a")
    lines.append("\u30c7\u30fc\u30bf\u306f\u6700\u5927\uff15\u65e5\u9045\u308c\u308b")
    lines.append("\u5834\u5408\u304c\u3042\u308a\u307e\u3059\u3002")

    return "<pre>" + "\n".join(lines) + "</pre>"
