"""Telegram HTML for the revenue reports — bilingual EN/JP like the download report."""

from datetime import date, datetime
from typing import Optional

from src.revenue.models import RevenueResult

ICONS = {"App Store": "\U0001f34e", "Google Play": "\U0001f916", "Huawei": "\U0001f4f1"}
JP_STORE = {"App Store": "App Store", "Google Play": "Google Play", "Huawei": "Huawei"}
SYMBOL = {"PHP": "₱", "USD": "$", "JPY": "¥", "KRW": "₩", "EUR": "€"}


def money(value: Optional[float], ccy: str = "PHP") -> str:
    if value is None:
        return "N/A"
    sym = SYMBOL.get(ccy.upper(), ccy.upper() + " ")
    return f"{sym}{value:,.0f}"


def _status(r: RevenueResult, lang: str) -> Optional[str]:
    if r.error_message:
        return "⚠️ Unavailable" if lang == "en" else "⚠️ 取得不可"
    if r.gross is None:
        return ("⏳ " + (r.note or "not published yet")) if lang == "en" else "⏳ 未公開"
    return None


def format_daily(results: list[RevenueResult], report_time: datetime, mtd: dict[str, dict],
                 ccy: str = "PHP", data_date: Optional[date] = None) -> str:
    """Daily estimate message. `mtd` = period_totals() keyed by platform key."""
    from src.revenue.history import PLATFORM_KEY  # local import: keep formatter pure

    day_total = sum(r.net or 0.0 for r in results if r.ok)
    day_gross = sum(r.gross or 0.0 for r in results if r.ok)
    any_ok = any(r.ok for r in results)
    mtd_net = sum(v["net"] for v in mtd.values())
    mtd_gross = sum(v["gross"] for v in mtd.values())
    date_label = (data_date or report_time.date()).strftime("%b %d")

    en = [
        "\U0001f4b0 B-Ticket Daily Revenue Report",
        f"\U0001f4c5 {report_time:%Y-%m-%d} (data: {date_label})",
        "",
    ]
    jp = [
        "\U0001f4b0 B-Ticket 日次売上レポート",
        f"\U0001f4c5 {report_time:%Y-%m-%d}（データ: {date_label}）",
        "",
    ]

    for r in results:
        icon = ICONS.get(r.store_name, "\U0001f4e6")
        key = PLATFORM_KEY.get(r.store_name, "")
        m = mtd.get(key, {})
        st_en, st_jp = _status(r, "en"), _status(r, "jp")
        en.append(f"{icon} {r.store_name}")
        jp.append(f"{icon} {JP_STORE.get(r.store_name, r.store_name)}")
        if st_en:
            en.append(f"   {st_en}")
            jp.append(f"   {st_jp}")
        else:
            txn = f" · {r.transactions} txn" if r.transactions else ""
            rf = f" · {r.refunds} refund" if r.refunds else ""
            en.append(f"   Gross: {money(r.gross, ccy)} | Net: {money(r.net, ccy)}{txn}{rf}")
            jp.append(f"   総額: {money(r.gross, ccy)} | 純額: {money(r.net, ccy)}{txn.replace('txn', '件')}{rf.replace('refund', '返金')}")
        if m:
            en.append(f"   MTD: {money(m['gross'], ccy)} gross | {money(m['net'], ccy)} net")
            jp.append(f"   月初来: 総額 {money(m['gross'], ccy)} | 純額 {money(m['net'], ccy)}")
        en.append("")
        jp.append("")

    bar = "━" * 30
    en += [
        bar,
        f"\U0001f4c8 Today Net: {money(day_total if any_ok else None, ccy)} (gross {money(day_gross if any_ok else None, ccy)})",
        f"\U0001f4e6 MTD Net: {money(mtd_net, ccy)} (gross {money(mtd_gross, ccy)})",
        "",
        "Auto-generated by AI",
        report_time.strftime("%I:%M %p PHT"),
        "",
        "Note: Google Play & Huawei net are",
        "estimates (fee applied by rate).",
        "Reconciled figures come in the",
        "monthly PDF.",
    ]
    jp += [
        bar,
        f"\U0001f4c8 本日純額: {money(day_total if any_ok else None, ccy)}（総額 {money(day_gross if any_ok else None, ccy)}）",
        f"\U0001f4e6 月初来純額: {money(mtd_net, ccy)}（総額 {money(mtd_gross, ccy)}）",
        "",
        "AI自動生成",
        report_time.strftime("%I:%M %p PHT"),
        "",
        "注: Google Play・Huaweiの純額は",
        "手数料率による推定値です。",
        "確定値は月次PDFを",
        "ご確認ください。",
    ]

    return "<pre>" + "\n".join(en + ["", bar, ""] + jp) + "</pre>"


def format_monthly_caption(results: list[RevenueResult], month_label: str, ccy: str = "PHP",
                           prev_net: Optional[float] = None) -> str:
    """Short HTML caption for the PDF document (Telegram caps captions at 1024 chars)."""
    net = sum(r.net or 0.0 for r in results if r.ok)
    gross = sum(r.gross or 0.0 for r in results if r.ok)
    lines = [
        f"<b>\U0001f4b0 B-Ticket Monthly Revenue — {month_label}</b>",
        f"Net {money(net, ccy)} · Gross {money(gross, ccy)}",
    ]
    if prev_net:
        delta = (net - prev_net) / prev_net * 100 if prev_net else 0.0
        arrow = "▲" if delta >= 0 else "▼"
        lines.append(f"{arrow} {delta:+.1f}% vs prior month")
    for r in results:
        icon = ICONS.get(r.store_name, "\U0001f4e6")
        if r.ok:
            tag = "" if r.basis == "reconciled" else " (est.)"
            lines.append(f"{icon} {r.store_name}: {money(r.net, ccy)}{tag}")
        else:
            lines.append(f"{icon} {r.store_name}: ⚠️ {r.note or 'unavailable'}")
    lines.append("")
    lines.append(f"\U0001f4b0 {month_label} 月次売上：純額 {money(net, ccy)}／総額 {money(gross, ccy)}")
    lines.append("詳細は添付PDFをご確認ください。")
    return "\n".join(lines)
